# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: kam-os
description: Eric's personal Fedora Atomic desktop

labels:
  org.opencontainers.image.source: "https://github.com/ericmeek/kam-os"

base-image: ghcr.io/ublue-os/base-main
image-version: 44

modules:

  #
  # Copy configuration files
  #
  - type: files
    files:
      - source: system
        destination: /

  #
  # RPM Packages
  #
  - type: dnf
    repos:
      copr:
        - atim/starship

    install:
      packages:

        #
        # Login
        #
        - greetd
        - tuigreet
        - dbus-tools

        #
        # Wayland
        #
        - niri
        - waybar
        - alacritty
        - mako
        - swaybg
        - swayidle
        - swaylock
        - wl-clipboard
        - grim
        - slurp
        - brightnessctl
        - playerctl
        - pavucontrol
        - xdg-desktop-portal-gtk

        #
        # File Management
        #
        - ffmpegthumbnailer
        - unar
        - 7zip
        - zstd
        - plocate

        #
        # Containers
        #
        - podman
        - podman-compose
        - distrobox

        #
        # Terminal Utilities
        #
        - git
        - vim
        - emacs
        - tmux
        - eza
        - fzf
        - ripgrep
        - fd-find
        - jq
        - tree
        - unzip
        - zip
        - rsync
        - curl
        - wget
        - fastfetch
        - btop
        - bat
        - du-dust
        - duf
        - ncdu
        - lsof
        - strace
        - starship

        #
        # Networking
        #
        - NetworkManager-tui

        #
        # Bluetooth
        #
        - blueman

        #
        # Fonts
        #
        - jetbrains-mono-fonts
        - fira-code-fonts
        - google-noto-fonts-all
        - fontawesome-fonts-all

    remove:
      packages:
        - firefox
        - firefox-langpacks
        - nano

  #
  # Flatpaks
  #
  - type: default-flatpaks
    configurations:

      - scope: system
        notify: true
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - com.github.tchx84.Flatseal
          - io.missioncenter.MissionCenter

      - scope: user

  - type: systemd
    system:
      enabled:
        - greetd.service
        - podman.socket
        - plocate-updatedb.timer

  - type: signing
